title: Sam Drew
description: A collection of writing about things I find interesting.
baseurl: ""
url: ""
twitter_username: sam__drew
github_username:  sam-drew

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

style: light

header_pages:
  - index.md
  - about.md
